// Merges per-category /tmp/details_N.json blobs (generated by content-writing agents)
// into docs/details.json, keyed by entry name — a persistent, checked-in source of truth.
const fs = require('fs');
const path = require('path');

const outPath = path.join(__dirname, '..', 'docs', 'details.json');
const existing = fs.existsSync(outPath) ? JSON.parse(fs.readFileSync(outPath, 'utf8')) : {};

const files = process.argv.slice(2);
if (files.length === 0) {
  console.error('Usage: node merge-details.js /tmp/details_0.json /tmp/details_1.json ...');
  process.exit(1);
}

let merged = 0;
for (const f of files) {
  const items = JSON.parse(fs.readFileSync(f, 'utf8'));
  for (const item of items) {
    if (!item.name) continue;
    existing[item.name] = {
      whatItIs: item.whatItIs || '',
      whyHelpful: item.whyHelpful || '',
      installNeeded: !!item.installNeeded,
      install: Array.isArray(item.install) ? item.install : [],
    };
    merged++;
  }
}

fs.writeFileSync(outPath, JSON.stringify(existing, null, 2) + '\n');
console.log(`Merged ${merged} entries from ${files.length} file(s) into docs/details.json (total ${Object.keys(existing).length}).`);
